import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Container from "../components/layouts/Container";
import Text from "../components/layouts/Text";
import HomeNavbar from "../layouts/HomeNavbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeNavbar />
      <main>
        <Container size="large">
          <Image width={256} height={256} src="/logo.svg" alt="logo" />
          <Text variant="xxl">Willkommen auf Programm Chest,</Text>
          <Text variant="caption">
            dem größten Programmier-Discord im deutschsprachigen Raum!
          </Text>
          <Button variant="primary">Join</Button>
        </Container>

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by me
          </a>
        </footer>
      </main>
    </div>
  );
};

export default Home;
