import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/layouts/Card";
import Container from "../components/layouts/Container";
import Flex from "../components/layouts/Flex";
import Text from "../components/layouts/Text";
import Anchor from "../components/Anchor";
import HomeNavbar from "../layouts/HomeNavbar";
import titleImage from "../public/title.jpg";
import Image from "next/future/image";
import { css } from "@emotion/react";
import React, { useEffect } from "react";
import Divider from "../components/layouts/Divider";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeNavbar />
      <main>
        <div css={css`
        background-image: url(${titleImage.src});
        background-size: cover;
        background-position: center;
      `}>
          <Container size="large" space="no" noBackground>
            <Image width={256} height={256} src="/logo.svg" alt="logo" />
            <div css={css`
            display: flex;
            flex-direction: column;
            gap: 1rem;
            background-color: rgba(0, 0, 0, 0.75);
            padding: 1rem;
            margin: 2rem;
            align-items: center;
            border-radius: 1rem;
          `}>
              <Text variant="xl">Willkommen auf</Text>
              <Text variant="xxl">Programm Chest</Text>
              <Text variant="caption">
                Dem größten Programmier-Discord im deutschsprachigen Raum!
              </Text>
              <Flex flexWrap="wrap" alignItems="center" justifyContent="center">
                <Anchor href="https://invite.programm-chest.dev" variant="primary">Join</Anchor>
                <Link href="/blog"><Anchor variant="secondary">Erkunden</Anchor></Link>
              </Flex>
            </div>
          </Container>
        </div>
        <Container>
          <Text variant="xxl" style={{ marginBottom: "2rem" }}>Was wir bieten</Text>
          <Flex alignItems="stretch" flexWrap="wrap" justifyContent="center" gap={12}>
            <Card title="Hilfsbereite Community" icon="live_help">
              Da wir viele Programmierer aus den unterschiedlichsten Bereichen und Themengebieten bei uns versammeln, wird sich sicherlich jemand finden, der die passende Lösung für dein Problem bereithält
            </Card>

            <Card title="Erfahrung" icon="schedule">
              Seit nun mehr als 3 Jahren kümmert sich unser Team gemeinsam mit unserer Community um Anliegen anderer Mitglieder.
            </Card>

            <Card title="Gemeinschaft" icon="diversity_1">
              Abseits von Fragen und Hilfe gibt es bei uns auch so manch eine hitzige Diskussion oder ein interessantes Gespräch. Auch Memes, Witze oder interessante Neuigkeiten sind bei uns natürlich gerne gesehen.
            </Card>
          </Flex>
        </Container>
        <Divider />
        <Container size="medium">
          <Text variant="xxl" style={{ marginBottom: "2rem" }}>Unser Discord</Text>
          <Flex alignItems="stretch" flexWrap="wrap" justifyContent="center" gap={24}>
            <iframe
              style={{ flex: 1, minHeight: "300px" }}
              src="https://discord.com/widget?id=543079984223223808&theme=dark"
              width="100%" height="100%s" frameBorder={0}
              sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
            <Flex flexDirection="column" flex={1} justifyContent="center">
              <Text variant="xl" align="left">Neugierig?</Text>
              <Text variant="m" align="left">
                Unsere Community freut sich immer wieder auf Neuzugänge.
                Falls du also ein Anliegen hast, das Programmieren leren möchtest
                oder einfach den ein oder anderen binären Artgenossen suchst,
                würden wir uns über deinen Besuch freuen.
              </Text>
              <Anchor href="https://invite.programm-chest.dev" size="small" style={{ alignSelf: 'flex-end' }}>Beitreten</Anchor>
            </Flex>
          </Flex>
        </Container>
        <Divider />
        <Container>
          <Text variant="xxl" style={{ marginBottom: "2rem" }}>Neuste Beiträge</Text>
          <Flex alignItems="stretch" flexWrap="wrap" justifyContent="center" gap={12}>
            {
              [1, 2, 3, 4, 5, 6].map((i) => (
                <Card title={`Title ${i}`} key={i} image={titleImage}>
                  <p>Da wir viele Programmierer aus den unterschiedlichsten Bereichen und Themengebieten bei uns versammeln, wird sich sicherlich jemand finden, der die passende Lösung für dein Problem bereithält</p>
                  <Anchor size="small" variant="secondary">Weiterlesen</Anchor>
                </Card>
              ))
            }
          </Flex>
        </Container>

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by me
          </a>
        </footer>
      </main>
    </div>
  );
};

export default Home;
